/**
 * DisclaimerModal.jsx
 *
 * Full-screen disclaimer shown on every fresh session.
 * Acceptance is persisted to localStorage under STORAGE_KEY so returning
 * users (same browser) are not interrupted on every page load.
 * Bumping STORAGE_KEY version forces all users to re-accept updated terms.
 */

import { useState } from "react";

const STORAGE_KEY = "wc2026-disclaimer-v1";

/** Call this from App.jsx to check whether the user has already accepted. */
export function hasAcceptedDisclaimer() {
  try { return localStorage.getItem(STORAGE_KEY) === "accepted"; }
  catch { return false; }
}

/** Persist acceptance so the modal won't re-appear this session/browser. */
export function persistAcceptance() {
  try { localStorage.setItem(STORAGE_KEY, "accepted"); }
  catch { /* storage blocked (private browsing, etc.) — degrade gracefully */ }
}

// ── Disclaimer sections ───────────────────────────────────────────────────────

const SECTIONS = [
  {
    heading: "1. Entertainment & Informational Use Only",
    body: `All match predictions, simulated scores, win probabilities, and bracket outcomes generated by this tool are produced by a statistical model for entertainment and informational purposes only. They do not constitute professional advice of any kind. No guarantee is made as to the accuracy, completeness, or fitness of any prediction for any particular purpose.`,
  },
  {
    heading: "2. No Liability for Betting or Gambling Losses",
    body: `This website is not a licensed gambling operator, bookmaker, or betting advisory service. Under no circumstances shall the owners, operators, contributors, or any associated party of this website be held liable for any financial losses, damages, costs, or expenses — including but not limited to losses incurred through sports betting, gambling, fantasy sports, or any other wagering activity — arising directly or indirectly from reliance on predictions or information displayed on this site.\n\nYou acknowledge and agree that any decision to place a bet or engage in gambling activity based on content from this site is made entirely at your own risk.`,
  },
  {
    heading: "3. Age Restriction — 18+ Only",
    body: `This website is intended solely for users who are 18 years of age or older (or the legal age of majority in your jurisdiction, whichever is higher). By continuing, you confirm that you meet this age requirement. If you are under 18, you must exit this site immediately.\n\nIf you are concerned about problem gambling, please contact the National Problem Gambling Helpline (US): 1-800-522-4700, or BeGambleAware (UK): 0808 8020 133.`,
  },
  {
    heading: "4. Model Accuracy & Data Limitations",
    body: `Predictions are generated using statistical models incorporating ELO ratings, historical match data, team form, and third-party prediction market odds (Polymarket). These inputs may be incomplete, out of date, or inaccurate. The model does not account for real-time squad changes, injuries, suspensions, weather conditions, managerial decisions, referee performance, or other factors that materially influence match outcomes.\n\nPast model accuracy (e.g. cross-validation scores) is provided for transparency only and does not guarantee future predictive performance.`,
  },
  {
    heading: "5. No Affiliation with FIFA or Tournament Organisers",
    body: `This is an independent, unofficial fan tool. It is not affiliated with, endorsed by, or connected to FIFA, CONMEBOL, UEFA, the 2026 FIFA World Cup Organising Committee, or any national football federation. All team names, competition names, and tournament branding are referenced solely for descriptive purposes.`,
  },
  {
    heading: "6. Third-Party Data & Intellectual Property",
    body: `This site references odds data from Polymarket, a third-party prediction market platform. Use of that data does not imply affiliation with or endorsement by Polymarket. Historical match statistics are sourced from publicly available datasets. All third-party trademarks remain the property of their respective owners.`,
  },
  {
    heading: "7. Prize Competition",
    body: `Any in-app prediction competition and associated prize (if applicable) is subject to the separate Rules & Prize Details document accessible from the site. The operator reserves the right to modify, suspend, or cancel the competition at any time without notice. Prize eligibility may be subject to geographic restrictions.`,
  },
  {
    heading: "8. Privacy",
    body: `If you choose to create an account, your email address and prediction data are stored securely via Supabase. We do not sell your personal data to third parties. By creating an account you consent to this storage. You may request deletion of your data at any time by contacting the site administrator.`,
  },
  {
    heading: "9. Changes to These Terms",
    body: `These terms may be updated at any time. Material changes will result in a new version of this disclaimer being presented to all users. Continued use of the site following updated terms constitutes acceptance.`,
  },
  {
    heading: "10. Governing Law",
    body: `These terms shall be governed by and construed in accordance with applicable law. Any disputes arising from use of this site shall be subject to the exclusive jurisdiction of the courts of the operator's place of incorporation. If any provision of these terms is found to be unenforceable, the remaining provisions shall remain in full force and effect.`,
  },
];

// ── Component ─────────────────────────────────────────────────────────────────

export default function DisclaimerModal({ onAccept }) {
  const [checked,  setChecked]  = useState(false);
  const [declined, setDeclined] = useState(false);

  function handleAccept() {
    if (!checked) return;
    persistAcceptance();
    onAccept();
  }

  // ── Declined screen ───────────────────────────────────────────────────────────
  if (declined) {
    return (
      <div
        className="fixed inset-0 z-[200] flex flex-col items-center justify-center px-6 text-center"
        style={{ background: "#0d0120" }}
      >
        <div className="text-5xl mb-4">🚫</div>
        <p
          className="font-black mb-2"
          style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: "2rem", color: "white", letterSpacing: "0.06em" }}
        >
          Access Denied
        </p>
        <p className="text-sm max-w-sm mb-6" style={{ color: "rgba(255,255,255,0.7)" }}>
          You must agree to the Terms of Use to access this site. Please close this tab or review the terms below.
        </p>
        <button
          onClick={() => setDeclined(false)}
          className="text-xs underline underline-offset-2"
          style={{ color: "rgba(200,240,0,0.6)" }}
        >
          ← Review Terms
        </button>
      </div>
    );
  }

  // ── Main modal ────────────────────────────────────────────────────────────────
  return (
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4"
      style={{ background: "rgba(10,2,28,0.97)", backdropFilter: "blur(8px)" }}
    >
      <div
        className="w-full max-w-2xl flex flex-col rounded-2xl overflow-hidden"
        style={{
          background: "#130828",
          border: "1px solid rgba(255,255,255,0.1)",
          boxShadow: "0 32px 80px rgba(0,0,0,0.8), 0 0 0 1px rgba(200,240,0,0.08)",
          maxHeight: "92vh",
        }}
      >
        {/* ── Header ── */}
        <div
          className="shrink-0 px-6 py-5 flex items-start gap-4"
          style={{ borderBottom: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.02)" }}
        >
          <div
            className="shrink-0 w-10 h-10 rounded-xl flex items-center justify-center text-lg"
            style={{ background: "rgba(245,158,11,0.15)", border: "1px solid rgba(245,158,11,0.25)" }}
          >
            ⚠️
          </div>
          <div>
            <p
              className="font-black leading-none mb-1"
              style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: "1.4rem", color: "white", letterSpacing: "0.06em" }}
            >
              Important Disclaimer &amp; Terms of Use
            </p>
            <p className="text-xs" style={{ color: "rgba(255,255,255,0.7)" }}>
              Please read carefully before accessing the FIFA World Cup 2026 Predictor.
              You must agree to these terms to continue.
            </p>
          </div>
        </div>

        {/* ── Scrollable body ── */}
        <div className="flex-1 overflow-y-auto px-6 py-5" style={{ minHeight: 0 }}>

          {/* Warning banner */}
          <div
            className="rounded-xl p-4 mb-5 flex items-start gap-3"
            style={{ background: "rgba(245,158,11,0.08)", border: "1px solid rgba(245,158,11,0.2)" }}
          >
            <span className="text-lg shrink-0 leading-none mt-0.5">🎰</span>
            <p className="text-xs leading-relaxed" style={{ color: "rgba(255,255,255,0.65)" }}>
              <span className="font-bold" style={{ color: "#f59e0b" }}>Gambling Warning: </span>
              Predictions on this site are <strong>not</strong> betting tips. The operator accepts{" "}
              <strong>no liability whatsoever</strong> for any financial losses arising from gambling
              or betting decisions made using this tool. Bet responsibly — or better yet, don&apos;t bet at all.
            </p>
          </div>

          {/* Sections */}
          <div className="flex flex-col gap-5">
            {SECTIONS.map(({ heading, body }) => (
              <div key={heading}>
                <p
                  className="text-xs font-black uppercase tracking-wider mb-1.5"
                  style={{ color: "#c8f000" }}
                >
                  {heading}
                </p>
                {body.split("\n\n").map((para, i) => (
                  <p
                    key={i}
                    className="text-xs leading-relaxed mb-2 last:mb-0"
                    style={{ color: "rgba(255,255,255,0.5)" }}
                  >
                    {para}
                  </p>
                ))}
              </div>
            ))}
          </div>

          {/* Responsible gambling links */}
          <div
            className="rounded-xl p-4 mt-6"
            style={{ background: "rgba(99,102,241,0.06)", border: "1px solid rgba(99,102,241,0.15)" }}
          >
            <p className="text-xs font-bold mb-2" style={{ color: "rgba(255,255,255,0.5)" }}>
              Responsible Gambling Resources
            </p>
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              {[
                { label: "BeGambleAware (UK)",  href: "https://www.begambleaware.org" },
                { label: "GamCare",             href: "https://www.gamcare.org.uk" },
                { label: "NCPG Helpline (US)",  href: "https://www.ncpgambling.org" },
                { label: "GamblingTherapy",     href: "https://www.gamblingtherapy.org" },
              ].map(({ label, href }) => (
                <a
                  key={label}
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs underline underline-offset-2 transition-colors"
                  style={{ color: "rgba(99,102,241,0.7)" }}
                  onMouseEnter={e => { e.currentTarget.style.color = "#a5b4fc"; }}
                  onMouseLeave={e => { e.currentTarget.style.color = "rgba(99,102,241,0.7)"; }}
                >
                  {label}
                </a>
              ))}
            </div>
          </div>
        </div>

        {/* ── Footer / actions ── */}
        <div
          className="shrink-0 px-6 py-4 flex flex-col gap-3"
          style={{ borderTop: "1px solid rgba(255,255,255,0.08)", background: "rgba(255,255,255,0.02)" }}
        >
          {/* Checkbox */}
          <label className="flex items-start gap-3 cursor-pointer select-none group">
            <div className="relative shrink-0 mt-0.5">
              <input
                type="checkbox"
                className="sr-only"
                checked={checked}
                onChange={e => setChecked(e.target.checked)}
              />
              <div
                className="w-4 h-4 rounded flex items-center justify-center transition-all"
                style={{
                  background:  checked ? "#c8f000" : "transparent",
                  border:      checked ? "1px solid #c8f000" : "1px solid rgba(255,255,255,0.25)",
                  boxShadow:   checked ? "0 0 8px rgba(200,240,0,0.4)" : "none",
                }}
              >
                {checked && (
                  <svg width="10" height="10" viewBox="0 0 10 10" fill="none">
                    <polyline points="1.5,5 4,7.5 8.5,2.5" stroke="#1a0533" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                )}
              </div>
            </div>
            <span className="text-xs leading-relaxed" style={{ color: "rgba(255,255,255,0.55)" }}>
              I confirm that I am <strong style={{ color: "rgba(255,255,255,0.8)" }}>18 years of age or older</strong>,
              I have read and understood the disclaimer above, and I agree to the Terms of Use.
              I acknowledge that predictions are for <strong style={{ color: "rgba(255,255,255,0.8)" }}>entertainment purposes only</strong> and
              I will not hold the operators liable for any losses arising from gambling or betting decisions.
            </span>
          </label>

          {/* Buttons */}
          <div className="flex items-center gap-3">
            <button
              onClick={handleAccept}
              disabled={!checked}
              className="flex-1 py-3 rounded-xl font-black text-sm transition-all duration-150 active:scale-95"
              style={{
                background: checked
                  ? "linear-gradient(135deg,#c8f000,#84cc16)"
                  : "rgba(255,255,255,0.07)",
                color:   checked ? "#1a0533" : "rgba(255,255,255,0.2)",
                cursor:  checked ? "pointer" : "not-allowed",
                boxShadow: checked ? "0 0 20px rgba(200,240,0,0.3)" : "none",
              }}
            >
              {checked ? "I Agree — Enter Site" : "Check the box above to continue"}
            </button>
            <button
              onClick={() => setDeclined(true)}
              className="px-4 py-3 rounded-xl text-xs font-semibold transition-all"
              style={{ color: "rgba(255,255,255,0.55)", border: "1px solid rgba(255,255,255,0.08)" }}
              onMouseEnter={e => { e.currentTarget.style.color = "#ef4444"; e.currentTarget.style.borderColor = "rgba(239,68,68,0.3)"; }}
              onMouseLeave={e => { e.currentTarget.style.color = "rgba(255,255,255,0.25)"; e.currentTarget.style.borderColor = "rgba(255,255,255,0.08)"; }}
            >
              Decline
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
