export const FLAG_CODES = {
  "Algeria":      "dz",
  "Argentina":    "ar",
  "Australia":    "au",
  "Austria":      "at",
  "Belgium":      "be",
  "Bosnia":       "ba",
  "Brazil":       "br",
  "Canada":       "ca",
  "Cape Verde":   "cv",
  "Colombia":     "co",
  "Croatia":      "hr",
  "Curaçao":      "cw",
  "Czechia":      "cz",
  "DR Congo":     "cd",
  "Ecuador":      "ec",
  "Egypt":        "eg",
  "England":      "gb-eng",
  "France":       "fr",
  "Germany":      "de",
  "Ghana":        "gh",
  "Haiti":        "ht",
  "Iran":         "ir",
  "Iraq":         "iq",
  "Ivory Coast":  "ci",
  "Japan":        "jp",
  "Jordan":       "jo",
  "Mexico":       "mx",
  "Morocco":      "ma",
  "Netherlands":  "nl",
  "New Zealand":  "nz",
  "Norway":       "no",
  "Panama":       "pa",
  "Paraguay":     "py",
  "Portugal":     "pt",
  "Qatar":        "qa",
  "Saudi Arabia": "sa",
  "Scotland":     "gb-sct",
  "Senegal":      "sn",
  "South Africa": "za",
  "South Korea":  "kr",
  "Spain":        "es",
  "Sweden":       "se",
  "Switzerland":  "ch",
  "Tunisia":      "tn",
  "Türkiye":      "tr",
  "USA":          "us",
  "Uruguay":      "uy",
  "Uzbekistan":   "uz",
};

// Returns the fi-* CSS class for flag-icons, or null if unknown
export function getFlagClass(name) {
  const code = FLAG_CODES[name];
  return code ? `fi fi-${code}` : null;
}
