-- Migration 011: idempotent terms acceptance + first-party activity analytics

-- ── Terms acceptance: one row per account/browser and terms version ─────────

alter table public.terms_acceptances
  add column if not exists anonymous_id uuid;

-- Keep the earliest legal acceptance when older clients produced duplicates.
delete from public.terms_acceptances t
using (
  select id
  from (
    select id,
           row_number() over (
             partition by user_id, version
             order by accepted_at asc, id asc
           ) as duplicate_number
    from public.terms_acceptances
    where user_id is not null
  ) ranked
  where duplicate_number > 1
) duplicates
where t.id = duplicates.id;

create unique index if not exists terms_acceptances_user_version_uidx
  on public.terms_acceptances (user_id, version)
  where user_id is not null;

create unique index if not exists terms_acceptances_browser_version_uidx
  on public.terms_acceptances (anonymous_id, version)
  where user_id is null and anonymous_id is not null;

-- ── Sessions ────────────────────────────────────────────────────────────────

create table if not exists public.app_sessions (
  id              uuid primary key,
  user_id         uuid references auth.users (id) on delete set null,
  anonymous_id    uuid not null,
  started_at      timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  active_seconds  integer not null default 0 check (active_seconds >= 0),
  page_views      integer not null default 0 check (page_views >= 0),
  entry_page      text,
  current_page    text,
  user_agent      text
);

create index if not exists app_sessions_started_at_idx
  on public.app_sessions (started_at desc);
create index if not exists app_sessions_last_seen_at_idx
  on public.app_sessions (last_seen_at desc);
create index if not exists app_sessions_user_id_idx
  on public.app_sessions (user_id) where user_id is not null;
create index if not exists app_sessions_anonymous_id_idx
  on public.app_sessions (anonymous_id);

alter table public.app_sessions enable row level security;

grant insert, update on public.app_sessions to anon, authenticated;
grant select on public.app_sessions to authenticated;

drop policy if exists "visitors can create their own sessions" on public.app_sessions;
create policy "visitors can create their own sessions"
  on public.app_sessions
  for insert
  to anon, authenticated
  with check (
    (auth.uid() is null and user_id is null) or
    (auth.uid() is not null and user_id = auth.uid())
  );

drop policy if exists "visitors can update their own sessions" on public.app_sessions;
create policy "visitors can update their own sessions"
  on public.app_sessions
  for update
  to anon, authenticated
  using (
    (auth.uid() is null and user_id is null) or
    (auth.uid() is not null and user_id = auth.uid())
  )
  with check (
    (auth.uid() is null and user_id is null) or
    (auth.uid() is not null and user_id = auth.uid())
  );

drop policy if exists "admins can read app sessions" on public.app_sessions;
create policy "admins can read app sessions"
  on public.app_sessions
  for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin
    )
  );

-- ── Activity events ─────────────────────────────────────────────────────────

create table if not exists public.app_activity_events (
  id            bigint generated by default as identity primary key,
  session_id    uuid not null references public.app_sessions (id) on delete cascade,
  user_id       uuid references auth.users (id) on delete set null,
  anonymous_id  uuid not null,
  event_name    text not null check (event_name ~ '^[a-z][a-z0-9_]{1,63}$'),
  page          text,
  metadata      jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at    timestamptz not null default now()
);

create index if not exists app_activity_events_created_at_idx
  on public.app_activity_events (created_at desc);
create index if not exists app_activity_events_session_id_idx
  on public.app_activity_events (session_id);
create index if not exists app_activity_events_name_created_idx
  on public.app_activity_events (event_name, created_at desc);
create index if not exists app_activity_events_user_id_idx
  on public.app_activity_events (user_id) where user_id is not null;

alter table public.app_activity_events enable row level security;

grant insert on public.app_activity_events to anon, authenticated;
grant select on public.app_activity_events to authenticated;
grant usage, select on sequence public.app_activity_events_id_seq to anon, authenticated;

drop policy if exists "visitors can record their own activity" on public.app_activity_events;
create policy "visitors can record their own activity"
  on public.app_activity_events
  for insert
  to anon, authenticated
  with check (
    (auth.uid() is null and user_id is null) or
    (auth.uid() is not null and user_id = auth.uid())
  );

drop policy if exists "admins can read app activity" on public.app_activity_events;
create policy "admins can read app activity"
  on public.app_activity_events
  for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin
    )
  );

-- ── Admin-only aggregate endpoint ───────────────────────────────────────────

create or replace function public.get_app_analytics(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  safe_days integer := greatest(7, least(coalesce(p_days, 30), 90));
  result jsonb;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin
  ) then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  with
  event_identities as (
    select
      e.created_at,
      e.session_id,
      e.user_id,
      e.anonymous_id,
      e.event_name,
      e.page,
      e.metadata,
      case
        when e.user_id is not null then 'user:' || e.user_id::text
        else 'anon:' || e.anonymous_id::text
      end as identity_key
    from public.app_activity_events e
  ),
  session_identities as (
    select
      s.*,
      case
        when s.user_id is not null then 'user:' || s.user_id::text
        else 'anon:' || s.anonymous_id::text
      end as identity_key
    from public.app_sessions s
  ),
  daily_series as (
    select generate_series(
      current_date - (safe_days - 1),
      current_date,
      interval '1 day'
    )::date as day
  ),
  daily_values as (
    select
      d.day,
      count(distinct e.identity_key) as active_users,
      count(distinct e.session_id) as sessions,
      coalesce(sum(
        case when e.event_name = 'heartbeat' and (e.metadata ->> 'active_seconds') ~ '^[0-9]+$'
          then greatest(0, least((e.metadata ->> 'active_seconds')::integer, 120))
          else 0
        end
      ), 0) as active_seconds
    from daily_series d
    left join event_identities e
      on e.created_at >= d.day::timestamptz
     and e.created_at < (d.day + 1)::timestamptz
    group by d.day
    order by d.day
  ),
  returning_users as (
    select identity_key, count(*) as session_count
    from session_identities
    where started_at >= now() - interval '30 days'
    group by identity_key
  ),
  popular_pages as (
    select page, count(*) as views
    from event_identities
    where event_name = 'page_view'
      and page is not null
      and created_at >= current_date - (safe_days - 1)
    group by page
    order by views desc, page
    limit 8
  ),
  popular_features as (
    select event_name, count(*) as uses
    from event_identities
    where event_name not in ('page_view', 'heartbeat', 'session_start')
      and created_at >= current_date - (safe_days - 1)
    group by event_name
    order by uses desc, event_name
    limit 8
  ),
  user_activity as (
    select
      e.user_id,
      p.username,
      p.avatar_url,
      u.email,
      count(distinct e.session_id) as sessions,
      count(*) filter (where e.event_name = 'page_view') as page_views,
      count(*) filter (
        where e.event_name not in ('page_view', 'heartbeat', 'session_start')
      ) as feature_actions,
      coalesce(sum(
        case when e.event_name = 'heartbeat' and (e.metadata ->> 'active_seconds') ~ '^[0-9]+$'
          then greatest(0, least((e.metadata ->> 'active_seconds')::integer, 120))
          else 0
        end
      ), 0) as active_seconds,
      max(e.created_at) as last_active_at
    from event_identities e
    left join public.profiles p on p.id = e.user_id
    left join auth.users u on u.id = e.user_id
    where e.user_id is not null
      and e.created_at >= current_date - (safe_days - 1)
    group by e.user_id, p.username, p.avatar_url, u.email
  ),
  ranked_user_activity as (
    select *
    from user_activity
    order by greatest(active_seconds, page_views * 30, sessions * 10) desc,
             last_active_at desc
    limit 100
  )
  select jsonb_build_object(
    'generated_at', now(),
    'range_days', safe_days,
    'dau', (
      select count(distinct identity_key) from event_identities
      where created_at >= current_date
    ),
    'wau', (
      select count(distinct identity_key) from event_identities
      where created_at >= current_date - 6
    ),
    'mau', (
      select count(distinct identity_key) from event_identities
      where created_at >= current_date - 29
    ),
    'sessions', (
      select count(*) from session_identities
      where started_at >= current_date - (safe_days - 1)
    ),
    'page_views', (
      select count(*) from event_identities
      where event_name = 'page_view'
        and created_at >= current_date - (safe_days - 1)
    ),
    'identified_users', (
      select count(distinct user_id) from event_identities
      where user_id is not null
        and created_at >= current_date - (safe_days - 1)
    ),
    'identified_page_views', (
      select count(*) from event_identities
      where event_name = 'page_view'
        and user_id is not null
        and created_at >= current_date - (safe_days - 1)
    ),
    'anonymous_page_views', (
      select count(*) from event_identities
      where event_name = 'page_view'
        and user_id is null
        and created_at >= current_date - (safe_days - 1)
    ),
    'identified_traffic_rate', (
      select case when count(*) = 0 then 0
        else round(100.0 * count(*) filter (where user_id is not null) / count(*), 1)
      end
      from event_identities
      where event_name = 'page_view'
        and created_at >= current_date - (safe_days - 1)
    ),
    'avg_active_seconds', (
      select coalesce(round(avg(active_seconds)), 0) from session_identities
      where started_at >= current_date - (safe_days - 1)
    ),
    'return_rate', (
      select case when count(*) = 0 then 0
        else round(100.0 * count(*) filter (where session_count > 1) / count(*), 1)
      end
      from returning_users
    ),
    'daily', (select coalesce(jsonb_agg(to_jsonb(daily_values) order by day), '[]'::jsonb) from daily_values),
    'popular_pages', (select coalesce(jsonb_agg(to_jsonb(popular_pages)), '[]'::jsonb) from popular_pages),
    'popular_features', (select coalesce(jsonb_agg(to_jsonb(popular_features)), '[]'::jsonb) from popular_features),
    'top_users', (
      select coalesce(
        jsonb_agg(to_jsonb(ranked_user_activity) order by active_seconds desc, page_views desc),
        '[]'::jsonb
      )
      from ranked_user_activity
    )
  ) into result;

  return result;
end;
$$;

revoke all on function public.get_app_analytics(integer) from public, anon;
grant execute on function public.get_app_analytics(integer) to authenticated;
